In [1]:
import numpy as np

In [2]:
D = np.loadtxt('sgb128_dist.txt')

In [3]:
print(D)

[[   0.  966. 1513. ... 1564. 2871.  348.]
 [ 966.    0. 2410. ...  198. 1917. 2541.]
 [1513. 2410.    0. ... 2217. 2673. 1570.]
 ...
 [1564.  198. 2217. ...    0.  321.  936.]
 [2871. 1917. 2673. ...  321.    0.   34.]
 [ 348. 2541. 1570. ...  936.   34.    0.]]


In [10]:
def dist(i, j):
    if j > i:
        return D[j][j-i-1]
    elif j == i:
        return 0
    else: 
        return D[i][i-j-1]

In [15]:
dist(29,53)

899.0